name: Build Flutter Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Build Windows App
        run: flutter build windows --release

      - name: Create MSIX installer
        run: flutter pub run msix:create

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-installer
          path: build/windows/msix/*.msix